// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpuoeafrnuzswsnxlpdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdW9lYWZybnV6c3dzbnhscGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcyMzYzNTksImV4cCI6MjEwMjgxMjM1OX0.FfA4DeOD_L8-6M7IUyYk_dXhsHcCIA33XoYXhzZFe2Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});